# .github/workflows/nix-check.yml
name: Nix flake check

on:
  push:
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - LICENSE

jobs:
  check:
    runs-on: macos-15  # native arm64 (Apple Silicon) runner
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Flake check
        run: nix flake check

      - name: Build (no activation)
        run: nix build .#darwinConfigurations.Hasnaats-MacBook-Air.system --no-link --show-trace
